name: harness-example
replicas: 1

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

createNamespace: true
namespace: ${infra.kubernetes.namespace}
    
canaryWeight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.Approval.output.approverInputs.canary>
stableWeight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.Approval.output.approverInputs.stable>
