name: harness-example-istio-ng
replicas: 1

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>
    
canaryWeight: <+execution.steps.canaryDepoyment.steps.Approval.output.approverInputs.canary>
stableWeight: <+execution.steps.canaryDepoyment.steps.Approval.output.approverInputs.stable>

canaryWeightDefault: <+execution.steps.primaryDepoyment.steps.Split_All_Traffic_to_Stable.output.approverInputs.canary>
stableWeightDefault: <+execution.steps.primaryDepoyment.steps.Split_All_Traffic_to_Stable.output.approverInputs.stable>
