name: harness-example-istio-ng
replicas: 1

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>
    
canaryWeight: 10
stableWeight: 90

canaryWeightDefault: 0
stableWeightDefault: 100
