name: harness-example-istio-ng
replicas: 1

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>
    
canaryWeight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.canaryDepoyment.steps.Approval.output.approverInputs.canary>
stableWeight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.canaryDepoyment.steps.Approval.output.approverInputs.stable>
