# harness.io/skip-file-for-deploy

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    harness.io/managed: true
  name: {{.Values.name}}-virtualservice
spec:
  hosts:
    - '*'
  gateways:
    - '{{.Values.name}}-gateway'
  tcp:
    - match:
        - port: 31400
      route:
        - destination:
            host: {{.Values.name}}-svc
            port:
              number: 9000
            subset: "canary"
          weight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.primaryDepoyment.steps.Split_All_Traffic_to_Stable.output.approverInputs.canary>
        - destination:
            host: {{.Values.name}}-svc
            port:
              number: 9000
            subset: "stable"
          weight: <+pipeline.stages.Istio_Deployment.spec.execution.steps.primaryDepoyment.steps.Split_All_Traffic_to_Stable.output.approverInputs.stable>
